### ISSUE TITLE
NullPointerException beim Konvertieren OSM zurück zu Courseplay 

### ISSUE THREAD

**Issue by Gadarol** [yankee42/courseplay-osm-converter#7]
Das kommt bei mir raus, wenn ich die bearbeiteten Kurse wieder von OSM nach Course konvertieren will. _(Quelle: zsorra, Modhoster.de)_

```
java.lang.NullPointerException
at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
at java.lang.Double.parseDouble(Unknown Source)
at com.github.yankee42.courseconvert.CourseOsmConverter.toCourseWaypoint(CourseOsmConverter.java:101)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.collect(Unknown Source)
at com.github.yankee42.courseconvert.CourseOsmConverter.saveCourseXml(CourseOsmConverter.java:62)
at com.github.yankee42.courseconvert.CourseOsmConverter.convertOsm(CourseOsmConverter.java:55)
at com.github.yankee42.courseconvert.gui.MainGui.tryOsmToCourse(MainGui.java:81)
at com.github.yankee42.courseconvert.gui.MainGui.osmToCourse(MainGui.java:59)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source) 
```

**Comment by janek89er** [comment]
habe das selbe Problem

**Comment by yankee42** [comment]
Das bedeutet, dass bei einem Punkt der `height`-Tag fehlt. Hast du einen neuen Punkt zu einem Kurs hinzugefügt? Das sollte natürlich funktionieren, ich habe aber nicht daran gedacht, dass der keine height hat. Ich muss testen, wie ich das am besten löse. Als workaround wäre es möglich bei neu angelegten Punkten den `height`-Tag manuell in JOSM hinzuzufügen.

**Comment by zsorra** [comment]
Hallo Yankee.
Ja, beim anpassen der Kurse habe ich auch den einen oder anderen neuen Punkt hinzugefügt.
Jetzt wo das bekannt ist, werde ich die Kurse nochmal abändern und mal versuchen den height-Tag manuell einzugeben, mal sehen ob es dann klappt.

**Comment by yankee42** [comment]
Hier ist nochmal eine neue Preview-Version, die sowohl mit den alten Dateien umgehen können soll, als auch neue Wegpunkte unterstützen sollte. Könntest du mit dieser nochmal testen?

[courseconvert.zip](https://github.com/yankee42/courseplay-osm-converter/files/3055203/courseconvert.zip)

**Comment by KarwendelHopper** [comment]
Wer ich?

**Comment by yankee42** [comment]
Da du in diesem Thread noch nicht beteiligt warst meinte ich dich zwar nicht direkt, aber du kannst natürlich gerne auch probieren ob es dir bei dir weiterhilft.

**Comment by KarwendelHopper** [comment]
;-) Nee. Ich hatte meine Kurse, die Du mir aufgezählt hast, schon gekillt. Jetzt gibts die die liefen.

**Comment by yankee42** [comment]
Das Archiv mit den Kursen bevor du sie "gekillt" hast, wäre im Ticket noch da ;-).

**Comment by KarwendelHopper** [comment]
Ja versuchs mal. Bei mir gehen die auch mit der anderen Version von Dir nicht auf.

**Comment by zsorra** [comment]
Hallo Yankee42,
hab jetzt mal die von dir verlinkte Version getestet und es sieht gut aus, keine Fehlermeldung.
Jetzt muss ich die Kurse nur noch im LS selber mal antesten ob alles passt.

mfG

**Comment by alex2ruote** [comment]
Hi Yankee42
My error log looks identical as the one posted by Gadarol, but I didn't add new points, I just slightly moved some of them to test the editing process. The error log shows every time but I managed to actually convert the OSM file, but inexplicably instead of being named courseplayManager.xml it was named courseStorage0001 and the original one was overwritten. I made sure to actually select the right file at the beginning, so I don't get why it would overwrite another one.
Feel free to answer in German, I'm just very bad at writing in it.
Thank you, 
Alex
[ErrorLog.txt](https://github.com/yankee42/courseplay-osm-converter/files/3065510/ErrorLog.txt)

**Comment by yankee42** [comment]
The problems should be fixed in version 1.0.5. If they reappear, please leave another comment.
